### ISSUE TITLE
Спеллчекинг: включение срабатывания спеллчекинга при любом нажатии

### ISSUE THREAD

**Issue by YurkiySlon** [connect/captal#12]
Т.к. после нахождения ошибочного слова спеллчекинг начинает срабатывать на каждое нажатие, а не только на пробел, то в случае продолжения написания параграфа без устранения ошибки в слове ранее, спеллчекинг начинает подсвечивать каждое недописанное слово. Что воспринимается как неожиданное поведение программы, т.к. до найденного слова с ошибкой такого не происходило. Необходимо, чтобы либо спеллчекинг всегда отрабатывал на каждое нажатие, либо отработку по любому символу вешать только в случае редактирования подсвеченного слова, а все остальные должны проверяться по нажатию на пробел/знак пунктуации.

**Comment by connect** [comment]
Изменено. Теперь спеллчек всегда срабатывает на нажатие: пробела и знаков препинания.
