### ISSUE TITLE
Спеллчекинг: сохранение положения подчеркиваний, когда это не нужно

### ISSUE THREAD

**Issue by YurkiySlon** [connect/captal#15]
Если в предложении найдено и подчеркнуто "багнутое" слово и если перед этим словом в других местах предложения начать удалять буквы, то "багнутое" слово сдвигается налево, а подчеркивание остается на старом месте, просто его длина укорачивается до места, где после "багнутого" слова идет пробел.

**Comment by connect** [comment]
исправлено
