### ISSUE TITLE
Добавить подключение "компонентов"

### ISSUE THREAD

**Issue by jumangee** [connect/captal#3]
Добавить ветку "Компоненты" в дереве проекта

Правый/двойной клик на "Компоненты" - отобразить список компонентов (окно)

Список всех доступных компонентов - /online/components/
Подключенные проекту компоненты - xml проекта, Book\components

> book
> 
> > components url="...components/include"
> > 
> > > load name="comp1" ver="1.0"
> > > load name="comp2" ver="1.0"
> > > ....

В окне компонентов, уже подключенные компоненты выделить цветом и/или флагом

**Comment by connect** [comment]
добавлено
