### ISSUE TITLE
При экспорте не выводятся тексты выделенных действий

### ISSUE THREAD

**Issue by YurkiySlon** [connect/captal#30]
При экспорте с установленной галкой вывода выделенных действий, выводятся только номера переходов, тексты не выводятся. В целом имеет смысл переделать этот момент, выполнять проверку на наличие в тексте выделенного перехода номера параграфа и если он там есть - не присоединять к выделенному переходу ссылку с номером из поля "Переход к", а делать ссылкой номер параграфа внутри текста перехода.

**Comment by connect** [comment]
исправлено
