### ISSUE TITLE
Переименование параграфа вызывает неконтролируемое поведение

### ISSUE THREAD

**Issue by jumangee** [connect/captal#4]
Вопроизвелось разными способами с разными эффектами

Всё начинается с попытки переименовать параграф, в одном случае это получилось, но после, уже в процессе дальнейшей работы (ввод текста) начались глюки, в другом случае, ещё во время ввода нового названия - ввод отменился, название стало "" (пустым), и создался новый параграф пустой.

**Comment by jumangee** [comment]
Возможно дело не в переименовании. Встречен эффект что ввод буквы "т" (русская) создаёт новый параграф. Текст вводился в блоке действия.

**Comment by jumangee** [comment]
Подобный же эффект при вводе буквы "n" в поле DO действия

**Comment by connect** [comment]
Возможно несколько багов. Два бага, вызываемые переименовыванием исправлены. Других пока не наблюдается.

**Comment by connect** [comment]
Создание нового параграфа при нажатии "n" или "т" могут быть связаны со срабатыванием хоткея Alt+N. К переименовыванию параграфа не относятся.
