### ISSUE TITLE
Убрать отображение названий блоков для текста и действий

### ISSUE THREAD

**Issue by jumangee** [connect/captal#6]

**Comment by jumangee** [comment]
К блокам текста и действий нет обращения "по названию", они не требуются в интерфейсе редактора
https://cloud.githubusercontent.com/assets/3863733/13994816/9ca6f58e-f137-11e5-9b06-6ec09ca83b18.jpg

**Comment by connect** [comment]
Пока сделал их псевдо-невидимыми (цветом фона). Имена блокам нужны уже хотя бы для использования навигатора.

**Comment by jumangee** [comment]
Имена блоков, если нужны, можно генерировать автоматически

**Comment by connect** [comment]
Сейчас так и сделано, генерируются автоматически

**Comment by connect** [comment]
Выполнено
